apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  clusterIP: 10.99.54.200
  clusterIPs:
  - 10.99.54.200
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  sessionAffinity: None
  type: ClusterIP