apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-16T10:16:09Z"
  labels:
    run: wordpress
  name: wordpress
  namespace: default
  resourceVersion: "20990"
  uid: 157beb37-12ba-494e-a2e8-31adc422bf4b
spec:
  clusterIP: 10.102.55.68
  clusterIPs:
  - 10.102.55.68
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31229
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
