---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-db
  name: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
      name: wp-db
    spec:
      containers:
        - image: mysql:5.7
          name: wp-db
          ports:
            - containerPort: 3306
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: default-token-49tkw
              readOnly: true
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: docker-config
                  key: BLOG_DB_NAME
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: docker-config
                  key: BLOG_DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: docker-config
                  key: BLOG_DB_PASSWORD
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: default-token-49tkw
          secret:
            defaultMode: 420
            secretName: default-token-49tkw