---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  ports:
  - nodePort: 31229
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-app
  type: NodePort