---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  clusterIP: 10.102.55.68
  clusterIPs:
  - 10.102.55.68
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31229
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-app
  sessionAffinity: None
  type: NodePort