---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-db
  name: wp-db
spec:
  clusterIP: 10.99.54.200
  clusterIPs:
  - 10.99.54.200
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wp-db
  sessionAffinity: None
  type: ClusterIP