---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-db
  name: wp-db
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wp-db
  type: ClusterIP